
spring:
  application:
    name: music

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试
  eager-load:
    enabled: true
    clients: distribution, material-product, outer-data


eureka:
  client:
    serviceUrl:
      defaultZone: http://su:admin@localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    hostname: music
    non-secure-port: 8083
    instance-id: MUSIC
server:
  port: 8083
logging:
  level:
    com.vabait.music.ProxyClient: DEBUG
